name: Build morthimer/caddy-homelab image
on: [push]

env:
  REGISTRY: https://git.int.morthimer.fr:8443
  CADDY_VERSION: 2.7.6
  CADDY_DOCKER_PROXY_VERSION: 2.8.11

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Repository login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ gitea.repository }}:latest
          build-args: |
            WEBSERVER_VERSION=${{ env.CADDY_VERSION }}
            DOCKER_PROXY_VERSION=${{ env.CADDY_DOCKER_PROXY_VERSION }}